[package]
name = "starkswap_contracts"
version = "0.1.0"
cairo-version = "2.1.0-rc4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra=true
casm=true

[dependencies]
starknet = ">=2.1.1"
#TODO: replace with real OZ once merged
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", branch = "cairo-2" }
