[package]
name = "starkswap_contracts"
version = "0.1.0"
cairo-version = "2.1.0-rc4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
[[target.starknet-contract]]
sierra=true
casm=true
allowed-libfuncs-list.name = "experimental_v0.1.0"
allowed-libfuncs=true
allowed-libfuncs-deny = false
casm-add-pythonic-hints = true

[dependencies]
starknet = ">=2.1.0-rc4"
#TODO: replace with real OZ once merged
openzeppelin = { git = "https://github.com/maciektr/cairo-contracts.git", branch = "maciektr/scarb-2" }
